// <auto-generated />
using System;
using LostAndFoundApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFoundApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226000000_AddAnnouncements")]
    partial class AddAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This file mirrors ApplicationDbContextModelSnapshot.cs
            // Content omitted as EF Core primarily uses the snapshot for diff detection
#pragma warning restore 612, 618
        }
    }
}
